sudo: required
services:
  - docker

before_install:
  - cd frontendapp
  - docker build -t erickgallani/kubernetestest -f Dockerfile.dev .

script:
  - docker run erickgallani/kubernetestest npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-us-west-2-285159751624"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"